let mapleader=" "
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz,ё;`,Ё;~
inoremap jk <Esc>
nnoremap Q :write<CR>
nnoremap <leader>w :write<CR>
nnoremap j h
nnoremap k j
nnoremap l k
nnoremap ; l
vnoremap j h
vnoremap k j
vnoremap l k
vnoremap ; l
nnoremap <C-y> "+y
vnoremap <C-y> "+y
nnoremap <Esc> :nohlsearch<CR>
nnoremap <C-D> <C-D>zz
nnoremap <C-U> <C-U>zz
nnoremap <leader>o :quickSwitcher<CR>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
